---
image: bunop/tskitetude:master

tasks:
  - name: install dependencies and start jupyter using poetry
    init: poetry install && poetry run nbstripout --install
    command: poetry run jupyter lab --no-browser --port=8888 --ip=*

vscode:
  extensions:
    - ms-python.python
    - ms-python.debugpy
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-slideshow
    - ms-toolsai.vscode-jupyter-cell-tags

ports:
  - port: 8888
  - port: 8080
