---
image: bunop/tskitetude:master

tasks:
  - name: install dependencies and start jupyter using poetry
    before: poetry install
    init: poetry run nbstripout --install
    command: poetry run jupyter lab --no-browser --port=8888 --ip=*

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers

ports:
  - port: 8888
  - port: 8080
